# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Heroku Deployment

on:
  push:
    branches: [ master ]

jobs:
  api-heroku-deploy:
    name: API Heroku Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: trending-topics-api
        heroku_email: kylewhitaker51@gmail.com
  client-heroku-deploy:
    name: Client Heroku Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: trending-topics-client
        heroku_email: kylewhitaker51@gmail.com
