# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  deploy-api:
    name: Heroku Deployment API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
      with:
        heroku_api_key: d874e2ee-8176-4ec3-a067-4ce9e9f82a26
        heroku_app_name: trending-topics-api
        heroku_email: kylewhitaker51@gmail.com
