# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  deploy-api:
    name: Heroku Deployment API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
      with:
        heroku_api_key: a040e29c-920b-4c5d-a3fa-383467cd5c53
        heroku_app_name: trending-topics-api
        heroku_email: kylewhitaker51@gmail.com

  deploy-client:
    name: Heroku Deployment Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
      with:
        heroku_api_key: a040e29c-920b-4c5d-a3fa-383467cd5c53
        heroku_app_name: trending-topics-client
        heroku_email: kylewhitaker51@gmail.com
